### ISSUE TITLE
module "org.kde.kirigami" version 2.5 is not installed

### ISSUE THREAD

**Issue by ikiruog** [Zren/plasma-applet-dailyforecast#1]
The plasmoid does not work on openSUSE Leap 15, KDE 5.12.6
![screenshot_20190201_131659](https://user-images.githubusercontent.com/29463106/52116982-a4141080-2623-11e9-86ca-a168ff4cc30a.png)

In openSUSE there are two packages kirigami:
1. kirigami version 1.1.0-lp150.1.11
2. kirigami2 version 5.45.0-lp150.1.1

**Comment by Zren** [comment]
My bad, it seems I only need "kirigami 2.3" to use FormLayout.

https://api.kde.org/frameworks/kirigami/html/classorg_1_1kde_1_1kirigami_1_1FormLayout.html

Plasma Frameworks 5.45 appears to have Kirigami 2.4 according to the git repo.

https://github.com/KDE/kirigami/blob/v5.45.0/src/kirigamiplugin.cpp#L157

To confirm this, try editing the following file:

`~/.local/share/plasma/plasmoids/com.github.zren.dailyforecast/contents/ui/config/ConfigGeneral.qml`

Then change `2.5` to `2.3` here: https://github.com/Zren/plasma-applet-dailyforecast/blob/master/package/contents/ui/config/ConfigGeneral.qml#L6

```qml
import QtQuick 2.0
import QtQuick.Controls 1.0
import QtQuick.Layouts 1.0
import org.kde.plasma.core 2.0 as PlasmaCore

// import org.kde.kirigami 2.5 as Kirigami
import org.kde.kirigami 2.3 as Kirigami

import "../lib"
```

To test, either restart plasmashell (relog) or run:

```
plasmawindowed com.github.zren.dailyforecast
```

If this fixes it for you, I'll update the widget. Sorry, the filename says `plasma5.12`, but I've been testing in Manjaro with `5.14`..

**Comment by ikiruog** [comment]
Yes. I replaced 2.5 to 2.3 and this fixed the problem in both your plasmoids.
Good job, thank you!

**Comment by Zren** [comment]
Fixed in v2
