### ISSUE TITLE
Plasma 6 support

### ISSUE THREAD

**Issue by huntantr** [Zren/plasma-applet-dailyforecast#11]
Are their any plans for a Plasma 6 port?

**Comment by Zren** [comment]
I'm finishing up porting my build scripts to Plasma6 / `metadata.json`, then I'll just spam releases for the 10 widgets I've got.

https://github.com/Zren/plasma-applet-lib/commits/master/

**Comment by Zren** [comment]
I've released a Plasma 6 widget here: https://www.pling.com/p/2137185/
